// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bot_traces.sql

package repository

import (
	"context"
	"encoding/json"
)

const createBotTrace = `-- name: CreateBotTrace :exec
INSERT INTO bot_traces
  (bot_id, method, request, response)
VALUES
  ($1, $2, $3, $4)
`

type CreateBotTraceParams struct {
	BotID    int64
	Method   string
	Request  *json.RawMessage
	Response json.RawMessage
}

func (q *Queries) CreateBotTrace(ctx context.Context, arg CreateBotTraceParams) error {
	_, err := q.db.ExecContext(ctx, createBotTrace,
		arg.BotID,
		arg.Method,
		arg.Request,
		arg.Response,
	)
	return err
}
