// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cache.sql

package repository

import (
	"context"
	"encoding/json"
)

const get = `-- name: Get :one
SELECT id, key, value, created_at, updated_at FROM cache WHERE
  key = $1
`

func (q *Queries) Get(ctx context.Context, key string) (Cache, error) {
	row := q.db.QueryRowContext(ctx, get, key)
	var i Cache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const set = `-- name: Set :one
INSERT INTO cache
  (key, value)
VALUES
  ($1, $2)
ON CONFLICT (key)
DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = EXCLUDED.updated_at
RETURNING id, key, value, created_at, updated_at
`

type SetParams struct {
	Key   string
	Value json.RawMessage
}

func (q *Queries) Set(ctx context.Context, arg SetParams) (Cache, error) {
	row := q.db.QueryRowContext(ctx, set, arg.Key, arg.Value)
	var i Cache
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
