// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO game_players (
  chat_id, user_id, first_name, last_name, username
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, chat_id, user_id, first_name, last_name, username, created_at, updated_at, removed_at
`

type CreatePlayerParams struct {
	ChatID    int64
	UserID    int64
	FirstName string
	LastName  string
	Username  string
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (GamePlayer, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.ChatID,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
	)
	var i GamePlayer
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RemovedAt,
	)
	return i, err
}

const createRound = `-- name: CreateRound :one
INSERT INTO game_rounds (
  chat_id, user_id, username
) VALUES (
  $1, $2, $3
) RETURNING id, chat_id, user_id, username, created_at, updated_at
`

type CreateRoundParams struct {
	ChatID   int64
	UserID   int64
	Username string
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (GameRound, error) {
	row := q.db.QueryRowContext(ctx, createRound, arg.ChatID, arg.UserID, arg.Username)
	var i GameRound
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.UserID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayers = `-- name: GetPlayers :many
SELECT id, chat_id, user_id, first_name, last_name, username, created_at, updated_at, removed_at FROM game_players WHERE
  chat_id = $1
`

func (q *Queries) GetPlayers(ctx context.Context, chatID int64) ([]GamePlayer, error) {
	rows, err := q.db.QueryContext(ctx, getPlayers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePlayer
	for rows.Next() {
		var i GamePlayer
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRounds = `-- name: GetRounds :many
SELECT
	game_rounds.id, game_rounds.chat_id, game_rounds.user_id, game_rounds.username, game_rounds.created_at, game_rounds.updated_at,
	game_players.username AS actual_username
FROM
	game_rounds
	LEFT JOIN game_players ON game_rounds.user_id = game_players.user_id
	AND game_rounds.chat_id = game_players.chat_id
WHERE
	game_rounds.chat_id = $1
`

type GetRoundsRow struct {
	ID             uuid.UUID
	ChatID         int64
	UserID         int64
	Username       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ActualUsername sql.NullString
}

func (q *Queries) GetRounds(ctx context.Context, chatID int64) ([]GetRoundsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRounds, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoundsRow
	for rows.Next() {
		var i GetRoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActualUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :many
UPDATE game_players SET
  first_name=$2, last_name=$3, username=$4, updated_at=NOW()
WHERE
  user_id = $1
RETURNING id, chat_id, user_id, first_name, last_name, username, created_at, updated_at, removed_at
`

type UpdatePlayerParams struct {
	UserID    int64
	FirstName string
	LastName  string
	Username  string
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) ([]GamePlayer, error) {
	rows, err := q.db.QueryContext(ctx, updatePlayer,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GamePlayer
	for rows.Next() {
		var i GamePlayer
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
