// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type GamePlayer struct {
	ID        uuid.UUID
	ChatID    int64
	UserID    int64
	FirstName string
	LastName  string
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
	RemovedAt sql.NullTime
}

type GameRound struct {
	ID        uuid.UUID
	ChatID    int64
	UserID    int64
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
