// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package repository

import (
	"context"
	"encoding/json"
)

const getSettings = `-- name: GetSettings :one
SELECT id, chat_id, key, value, created_at, updated_at FROM chat_settings WHERE
  chat_id = $1 AND key = $2
`

type GetSettingsParams struct {
	ChatID int64
	Key    string
}

func (q *Queries) GetSettings(ctx context.Context, arg GetSettingsParams) (ChatSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettings, arg.ChatID, arg.Key)
	var i ChatSetting
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSettings = `-- name: SetSettings :one
INSERT INTO chat_settings
  (chat_id, key, value)
VALUES
  ($1, $2, $3)
ON CONFLICT (chat_id, key)
DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = EXCLUDED.updated_at
RETURNING id, chat_id, key, value, created_at, updated_at
`

type SetSettingsParams struct {
	ChatID int64
	Key    string
	Value  json.RawMessage
}

func (q *Queries) SetSettings(ctx context.Context, arg SetSettingsParams) (ChatSetting, error) {
	row := q.db.QueryRowContext(ctx, setSettings, arg.ChatID, arg.Key, arg.Value)
	var i ChatSetting
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
