CREATE TABLE IF NOT EXISTS cache (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  key TEXT NOT NULL,
  value JSONB NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE(key)
);